---
service_conf:
  service:
    name: spotless-liquid
    listen_addr: 0.0.0.0:3000
    discover_addr: http://127.0.0.1:3000
    timeout: 30
    concurrency_limit: 5120
    load_shed: false
  cert_file:
  key_file:
etcd:
  endpoints:
    - 127.0.0.1:2379
  user:
  keep_alive_while_idle: true
